package post_requests;

import base_urls.JsonPlaceHolderBaseUrl;
import io.restassured.http.ContentType;
import io.restassured.path.json.JsonPath;
import io.restassured.response.Response;
import org.junit.Test;

import static io.restassured.RestAssured.given;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;

public class Post01 extends JsonPlaceHolderBaseUrl {
    /*
    Given
      1) https://jsonplaceholder.typicode.com/todos
      2)  {
            "userId": 55,
            "title": "Tidy your room",
            "completed": false
         }
         OR
   NOTE:      payload {"userId": 55,"title": "Tidy your room","completed": false}
      3) Content type should be json
   When
       I send POST Request to the Url
   Then
       Status code is 201
   And
       response body is like
                    {
                       "userId": 55,
                       "title": "Tidy your room",
                       "completed": false,
                       "id": 201
                     }
     */

    @Test
    public void post01(){

        // Set the url
        spec.pathParam("first","todos");

        // Set the expected data (payload => the data that you want to transfer to the server)
        String payload ="{\n" +
                "            \"userId\": 55,\n" +
                "            \"title\": \"Tidy your room\",\n" +
                "            \"completed\": false\n" +
                "         }"; //Not recommended way

        System.out.println("payload = " + payload);
        //data type is string

        // Send the request and get the response
        Response response = given(spec).when().body(payload).post("{first}"); //.contentType(ContentType.JSON)
        //contentType(ContentType.JSON) can be here or in JsonPlaceHolderBaseUrl. Ideally it should be in the baseUrl class
        response.prettyPrint();

        // Do Assertions
        //Use JsonPath to extract the data out of the response body for assertion
        JsonPath jsonPath = response.jsonPath();
        assertEquals(201, response.statusCode());
        assertEquals(55, jsonPath.getInt("userId"));
        assertEquals("Tidy your room", jsonPath.getString("title"));
        //assertEquals(false, jsonPath.getBoolean("completed")); //below line is recommended by IntelliJ
        assertFalse(jsonPath.getBoolean("completed"));

        //NOTE: We don't assert ids because in real life, the ids are generated by the system
        // and the id will be different everytime you send any API requests


    }


}
